version: '4.22.1'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: facebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minh123
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: